config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#top'
  resources :art_crafts, only: [:show] do
    resources :comments
    resources :favorites, only: [:show, :create, :destroy]
    get 'search', on: :collection
    get 'favorite', on: :collection
  end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art_craft.rb
class ArtCraft < ApplicationRecord
  has_many :comments
  has_many :favorite_art_crafts
  enum category: { comics: 1, animes: 2 }
  
  DISPLAY_CATEGORY = {
    comics: 'マンガ',
    animes: 'アニメ'
  }
  
  def display_category
    DISPLAY_CATEGORY[category.to_sym]
  end
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :art_craft
end

app/models/favorite_art_craft.rb
class FavoriteArtCraft < ApplicationRecord
  belongs_to :user
  belongs_to :art_craft
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :favorite_art_crafts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/art_crafts_controller.rb
class ArtCraftsController < ApplicationController
  def show
    @art_craft = ArtCraft.find(params[:id])
    @favorite_art_craft = @art_craft.favorite_art_crafts.find_by(user: current_user)
    @comment = Comment.new
    @comments = @art_craft.comments.order(id: :desc).page(params[:page]).per(10)
  end
  
  def search
    @keyword = params[:keyword]
    @art_crafts = if @keyword
                    ArtCraft.where('title like ?', "%#{@keyword}%")
                  else
                    ArtCraft.all
                  end
  end
  
  def favorite
    art_craft_ids = current_user&.favorite_art_crafts&.pluck(:art_craft_id)
    @comics = ArtCraft.comics.where(id: art_craft_ids)
    @animes = ArtCraft.animes.where(id: art_craft_ids)
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @art_craft = ArtCraft.find(params[:art_craft_id])
    @comment = @art_craft.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to art_craft_path(@comment.art_craft), notice: 'Comment was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:user_id, :art_craft_id, :content)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @art_craft = ArtCraft.find(params[:art_craft_id])
    @favorite_art_craft = @art_craft.favorite_art_crafts.new
    @favorite_art_craft.user = current_user

    @favorite_art_craft.save
    redirect_to art_craft_path(@favorite_art_craft.art_craft), notice: 'favorite_art_craft was successfully registrated.'
  end

  def destroy
    @art_craft = ArtCraft.find(params[:art_craft_id])
    @favorite_art_craft = @art_craft.favorite_art_crafts.find(params[:id])
    @favorite_art_craft.destroy
    redirect_to art_craft_path(@art_craft), notice: 'favorite_art_craft was successfully destroyed.'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @comics = ArtCraft.comics.limit(5)
    @animes = ArtCraft.animes.limit(5)
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/art_crafts_helper.rb
module ArtCraftsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/art_crafts/favorite.html.erb
<%#<%= link_to 'お気に入り', art_craft_favorite_path(@art_craft, @favorite_art_craft), method: 'show', class: "nav-item nav-link" %>

<div class="container">
  <div class="row p-3">
    <div class="col-12 p-3 favorite-message">
      Your favorite<br/>
      &ensp;&ensp;Manga/Anime</br>
    </div>
  </div>
  
  <% if user_signed_in? %>
    <div class="row p-3">
      <div class="col-6 p-3 manga_favorites">
        <h3>お気に入りマンガ</h3>
        <ul class="list-group list-group-flush">
          <% @comics.each  do |comic| %>
            <li class="list-group-item"><%= link_to comic.title, art_craft_path(comic.id) %></li>
          <% end %>
        </ul>
      </div>

      <div class="col-6 p-3 anime_favorites">
        <h3>お気に入りアニメ</h3>
        <ul class="list-group list-group-flush">
          <% @animes.each  do |anime| %>
            <li class="list-group-item"><%= link_to anime.title, art_craft_path(anime.id) %></li>
          <% end %>
        </ul>
      </div>
    </div>
    
  <% else %>
    <div class="mx-auto" style="width: 200px;">
      <%= link_to "ログインしてお気に入り一覧を表示", new_user_session_path, class: 'btn btn-outline-secondary' %>
    </div>
    
  <% end %>

app/views/art_crafts/search.html.erb
<div class="container">
  <div class="row p-3">
    <div class="col-12 p-3 search-message">
      Great encounters are<br/>
      &ensp;&ensp;right there...</br>
    </div>
  </div>
  <div class="row">
    <div class="col-12 p-3">
      <%= form_tag(search_art_crafts_path, method: 'get') do %>
        <div class="input-group mb-3">
          <input type="text" name="keyword" value="<%= @keyword %>" class="form-control" placeholder="キーワードで探す" aria-label="Comment text" aria-describedby="button-addon2">
          <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="submit" id="button-addon2">検索</button>
          </div>
        </div>
      <% end %>
      <ul class="list-group list-group-flush">
        <% @art_crafts.each  do |art_craft| %>
          <li class="list-group-item">
            <% if art_craft.category === "comics" %>
              <%= link_to art_craft.title, art_craft_path(art_craft.id) %>
              <span class="badge badge-light"><%= art_craft.display_category %></span>
            <% else %>
              <%= link_to art_craft.title, art_craft_path(art_craft.id) %>
              <span class="badge badge-dark"><%= art_craft.display_category %></span>
            <% end %>
          </li>
        <% end %>
      </ul>
      <% if @art_crafts.empty? %>
        <p><%= @keyword %>にヒットする作品は見つかりませんでした。</p>
      <% end %>
    </div>
  </div>
</div>

app/views/art_crafts/show.html.erb
<div class="container">
   <div class="row p-3">
     <div class="col-10 p-3"><%= @art_craft.title %></div>
     <div class="col-2 p-3 text-right">
       <% if user_signed_in? %> 
         <% if @favorite_art_craft %>
           <%= link_to art_craft_favorite_path(@art_craft, @favorite_art_craft), method: 'delete' do %> 
             <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-heart-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
               <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
             </svg>
           <% end %>
         <% else %>
           <%= link_to art_craft_favorites_path(@art_craft), method: 'post' do %>
             <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-heart" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
               <path fill-rule="evenodd" d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
             </svg>
           <% end %>
         <% end %>
       <% end %>
     </div>
   </div>
      
   <% @comments.reverse.each do |comment| %>
     <div class="ml-3"><%= comment.user.name %></div>
     <div class="popover right show mx-3 mb-3 mt-1 p-1" style="position:relative; max-width:100%;">
       <div class="arrow"></div>
       <div class="popover-content">
         <p>
           <%= comment.content %>
         </p>
       </div>
     </div>
   <% end %>
    
   <%= paginate @comments %>
   <div class="container">
     <% if user_signed_in? %>
       <%= form_for(@comment, url: art_craft_comments_path(@art_craft)) do |f| %>
         <div class="row p-5">
           <div class="input-group mb-3">
             <%= f.text_field :content, class: "form-control", placeholder: "コメント投稿" %>
             <div class="input-group-append">
               <%= f.submit "送信", class: "btn btn-outline-secondary" %>
             </div>
           </div>
          </div>
       <% end %>
      <% else %>
         <div class="row p-5">
           <%= link_to "ログインしてコメントを投稿", new_user_session_path, class: 'btn btn-outline-secondary' %>
         </div> 
      <% end %>
   </div>
</div>

app/views/home/top.html.erb
<div class="container">
  <div class="row p-3">
    <div class="col-12 p-3 site-message">
      <h2>Manga/Anime <br/>
          &ensp;&ensp;Fan Community<br/>
      </h2>
      <h5>
        <br></br>
        マンガ/アニメ好きのためのコミュニティサイト<br></br>
        &ensp;&ensp;好きな作品で語り合おう！<br></br>
      </h5>
    </div>
  </div>
  <div class="row">
    <div class="col-6 p-3">
      <h3>人気マンガ</h3>
      <br></br>
      <ul class="list-group list-group-flush">
        <% @comics.each  do |comic| %>
          <li class="list-group-item"><%= link_to comic.title, art_craft_path(comic.id) %></li>
        <% end %>
      </ul>
    </div>
    <div class="col-6 p-3">
      <h3>人気アニメ</h3>
      <br></br>
      <ul class="list-group list-group-flush">
        <% @animes.each  do |anime| %>
          <li class="list-group-item"><%= link_to anime.title, art_craft_path(anime.id) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div class="container">
    <div class="col-6 p-3 information">
      イベント情報
    </div>
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <svg class="bd-placeholder-img bd-placeholder-img-lg d-block w-100" width="700" height="200" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: First slide">
            <title>Placeholder</title>
            <rect width="100%" height="80%" fill="#666"/>
            <text x="50%" y="30%" fill="#444" dy=".3em">
              First
            </text>
          </svg>
        </div>
        <div class="carousel-item">
          <svg class="bd-placeholder-img bd-placeholder-img-lg d-block w-100" width="700" height="200" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Second slide">
            <title>Placeholder</title>
            <rect width="100%" height="80%" fill="#666"/>
            <text x="50%" y="30%" fill="#444" dy=".3em">
              Second
            </text>
          </svg>
        </div>
        <div class="carousel-item">
          <svg class="bd-placeholder-img bd-placeholder-img-lg d-block w-100" width="700" height="200" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Third slide">
            <title>Placeholder</title>
            <rect width="100%" height="80%" fill="#666"/>
            <text x="50%" y="30%" fill="#444" dy=".3em">
              Third
            </text>
          </svg>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MangaAnime</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Caveat" rel="stylesheet">
    <link href="https://fonts.googleapis.com/earlyaccess/kokoro.css" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand " href="#">ロゴ</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= link_to 'HOME', root_path, class: "nav-item nav-link" %>
          <%= link_to '検索', search_art_crafts_path, class: "nav-item nav-link" %>
          <%= link_to 'お気に入り', favorite_art_crafts_path, class: "nav-item nav-link" %>
          <% if user_signed_in? %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-item nav-link' %>
          <% else %>
            <%= link_to "ログイン", new_user_session_path, class: 'post nav-item nav-link' %>
          <% end %>
        </div>
      </div>
    </nav>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  </body>
</html>